### ISSUE TITLE
SocketSender: Software caused connection abort is not passed to IConnectionInterface

### ISSUE THREAD

**Issue by daniel-stoneuk** [BoardiesITSolutions/Android-MySQL-Connector#19]
**Describe the bug**
When the connection is lost (for example, if data is turned off) none of the Exception callbacks are called. 

**To Reproduce**
1. Connect to mysql database
2. Disable Wifi and mobile data

**Expected behavior**
The error is passed to the callbacks passed to the connection.

**Comment by boardy** [comment]
how you managing to find all the bugs :)

Is it after you disable wifi and mobile data and you then go to run a query the error callback isn't being triggered and nothing happens or it just crashes, or are you expecting the library to throw an error straight after disabling data?

If the former where you run a query and the error callback isn't being triggered, are you giving it enough time to trigger, as it might take up to 30 seconds for a TCP timeout to occur. The library doesn't check the wifi/mobile data state as I think it requires extra permissions that might put some users off - but I can look into this in case that isn't correct.

**Comment by daniel-stoneuk** [comment]
My hostname is a local ip address and I expect it should lose connection once WiFi is turned off. If I turn off both WiFi and mobile data I get the following logs:

`E/SocketSender: java.net.ConnectException: failed to connect to /192.168.1.112 (port 3306) from /:: (port 38458): connect failed: ECONNABORTED (Software caused connection abort)`

I expected this to be passed to the IConnectionInterface so that I can show an error message. I've waited a long while and nothing yet!

I don't think we'll need to monitor the connection state - it's just that SocketSender currently doesn't pass the IO Exception on 59 to the interface, and then exceptions that occur on line 307 in Connection.java aren't being sent anywhere either. Could we just pass this to the connectionInterface?

![image](https://user-images.githubusercontent.com/15860949/89541554-6edb1680-d7f6-11ea-9742-b7b21b2b52c0.png)

**Comment by boardy** [comment]
Ah I see, the IConnectionInterface is at a higher lever error handling in terms of direct MySQL errors, this error is happening at a lower level. I'll probably need to see if I can pass the IConnectionInterface into the SocketSender constructor so that when the SocketSender itself throws a lower level error, it can bubble up into IConnectionInterface. 

I'll take a look at see how that would be implemented - a while since I wrote that part of the code.

I'll keep you updated. 

Thanks

Chris

**Comment by boardy** [comment]
I've push out 0.44_MySQL8 which allows the socket sender to throw an IOException and pass that back to the IConnectionResult interface instead of it just throwing an error exception internally. 

JitPack is currently building it though so its not available yet - its been going for around 30 minutes - this has happened once before where JitPack for some reason took a really long time to make it available so hopefully all being well it should be available in the not too distant future. 

Thanks 
Chris

**Comment by boardy** [comment]
There was an issue with 0.44 release for JitPack so you can use 0.45_MySQL8 instead

**Comment by daniel-stoneuk** [comment]
Hi Chris,

This is perfect. Thank you for taking the time to fix this, and for being so responsive here on GitHub. Been a lifesaver for the project I'm working on! I'm now able to show a message if the connection was lost which is fantastic. 

Let me know if you have a donations link or anywhere I can send some appreciation for the time you've saved me with this :)

**Comment by boardy** [comment]
No problem at all, glad its working for you now. 

I don't have any donation links anywhere but thank you for offering, much appreciated. 

Any other issues though let me know :)

Thanks
Chris

**Comment by daniel-stoneuk** [comment]
I wasn't able to get the byte array from the server making any sense - it was always different to the byte array that I would send to the database. Luckily client didn't need this as a feature (just upload). Thanks for your help!
